# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
